version: '3.3'

services:
  webserver:
    build: ./docker/webserver
    image: runwaytest_web
    ports:
      - "3000:80"
      - "3443:443"
    volumes:
      - /Users/varpiux/web-dev/sito-scuola/www:/var/www/html
    #- C:\Users\avaprio.IRIDES\sito-scuola\www:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "3396:3306"
    volumes:
      - /Users/varpiux/web-dev/sito-scuola/db:/var/lib/mysql
     # - C:\Users\avaprio.IRIDES\sito-scuola\db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_mysite
      
#docker-compose up -d --build